"""added interests/tag-followers relationship

Revision ID: 3001345478e9
Revises: 8f3a6e501af3
Create Date: 2019-02-03 14:35:00.411694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3001345478e9'
down_revision = '8f3a6e501af3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trainee_tag_relation',
    sa.Column('trainee_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.ForeignKeyConstraint(['trainee_id'], ['trainee.user_id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trainee_tag_relation')
    # ### end Alembic commands ###
