"""empty message

Revision ID: 428a9f4d5772
Revises: 
Create Date: 2018-12-27 21:45:37.023850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '428a9f4d5772'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trainee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('fullname', sa.String(length=120), nullable=True),
    sa.Column('gender', sa.Boolean(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('academic_level', sa.String(), nullable=True),
    sa.Column('user_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trainee_email'), 'trainee', ['email'], unique=True)
    op.create_index(op.f('ix_trainee_fullname'), 'trainee', ['fullname'], unique=False)
    op.create_index(op.f('ix_trainee_username'), 'trainee', ['username'], unique=True)
    op.create_table('trainer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('fullname', sa.String(length=120), nullable=True),
    sa.Column('gender', sa.Boolean(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('user_type', sa.String(), nullable=True),
    sa.Column('specialization', sa.String(length=180), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trainer_email'), 'trainer', ['email'], unique=True)
    op.create_index(op.f('ix_trainer_fullname'), 'trainer', ['fullname'], unique=False)
    op.create_index(op.f('ix_trainer_username'), 'trainer', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trainer_username'), table_name='trainer')
    op.drop_index(op.f('ix_trainer_fullname'), table_name='trainer')
    op.drop_index(op.f('ix_trainer_email'), table_name='trainer')
    op.drop_table('trainer')
    op.drop_index(op.f('ix_trainee_username'), table_name='trainee')
    op.drop_index(op.f('ix_trainee_fullname'), table_name='trainee')
    op.drop_index(op.f('ix_trainee_email'), table_name='trainee')
    op.drop_table('trainee')
    # ### end Alembic commands ###
