"""Add filetype to UserMedia

Revision ID: 9434790fb0c9
Revises: 39686d60064b
Create Date: 2019-01-19 20:05:48.304173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9434790fb0c9'
down_revision = '39686d60064b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_media', sa.Column('filetype', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_media', 'filetype')
    # ### end Alembic commands ###
