"""empty message

Revision ID: b162881c34f7
Revises: fb8c2ffded4b
Create Date: 2018-12-28 21:41:18.265657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b162881c34f7'
down_revision = 'fb8c2ffded4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lecture_room', sa.Column('activated', sa.Boolean(), nullable=True))
    op.add_column('trainee', sa.Column('activated', sa.Boolean(), nullable=True))
    op.add_column('trainer', sa.Column('activated', sa.Boolean(), nullable=True))
    op.add_column('training_center', sa.Column('activated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_center', 'activated')
    op.drop_column('trainer', 'activated')
    op.drop_column('trainee', 'activated')
    op.drop_column('lecture_room', 'activated')
    # ### end Alembic commands ###
