"""empty message

Revision ID: daa471c4c8b8
Revises: b162881c34f7
Create Date: 2018-12-29 17:47:27.720685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daa471c4c8b8'
down_revision = 'b162881c34f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lecture_room', sa.Column('user_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lecture_room', 'user_type')
    # ### end Alembic commands ###
