"""Add lecture room and centers

Revision ID: fb8c2ffded4b
Revises: 428a9f4d5772
Create Date: 2018-12-28 19:29:49.557731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb8c2ffded4b'
down_revision = '428a9f4d5772'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lecture_room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('fullname', sa.String(length=120), nullable=True),
    sa.Column('gender', sa.Boolean(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('room_name', sa.String(length=180), nullable=True),
    sa.Column('address', sa.String(length=180), nullable=True),
    sa.Column('fees', sa.Integer(), nullable=True),
    sa.Column('chairs', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lecture_room_email'), 'lecture_room', ['email'], unique=True)
    op.create_index(op.f('ix_lecture_room_fullname'), 'lecture_room', ['fullname'], unique=False)
    op.create_index(op.f('ix_lecture_room_username'), 'lecture_room', ['username'], unique=True)
    op.create_table('training_center',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('fullname', sa.String(length=120), nullable=True),
    sa.Column('gender', sa.Boolean(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('center_name', sa.String(length=180), nullable=True),
    sa.Column('specialization', sa.String(length=180), nullable=True),
    sa.Column('address', sa.String(length=180), nullable=True),
    sa.Column('user_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_center_email'), 'training_center', ['email'], unique=True)
    op.create_index(op.f('ix_training_center_fullname'), 'training_center', ['fullname'], unique=False)
    op.create_index(op.f('ix_training_center_username'), 'training_center', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_center_username'), table_name='training_center')
    op.drop_index(op.f('ix_training_center_fullname'), table_name='training_center')
    op.drop_index(op.f('ix_training_center_email'), table_name='training_center')
    op.drop_table('training_center')
    op.drop_index(op.f('ix_lecture_room_username'), table_name='lecture_room')
    op.drop_index(op.f('ix_lecture_room_fullname'), table_name='lecture_room')
    op.drop_index(op.f('ix_lecture_room_email'), table_name='lecture_room')
    op.drop_table('lecture_room')
    # ### end Alembic commands ###
